### ISSUE TITLE
Why you are hiding the content of viewer.js?

### ISSUE THREAD

**Issue by SleepWalker** [xiguaxigua/docusaurus-plugin-drawio#1]
Why you are hiding the contents of viewer.js?

**Comment by xiguaxigua** [comment]
Because it is not necessary to customize viewer.js in most cases, the logic of current viewer.js is hidden inside for the sake of simplification of configuration. However, now I think it is necessary to provide configuration to developers. If you have time If so, welcome to submit a pull request, otherwise I will deal with this issue at the end of this week
